# Generated by scripts/update-homebrew.sh; do not edit by hand.
class Noida < Formula
  desc "Terminal IDE built around Claude Code and Codex"
  homepage "https://github.com/its-banana-coder/noida"
  version "0.1.3-alpha"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.3-alpha/noida-aarch64-apple-darwin.tar.gz"
      sha256 "03e9ba1100743af2640075f5c71d404af6119a591ecc9e0d5bdc07aa495af45a"
    end
    on_intel do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.3-alpha/noida-x86_64-apple-darwin.tar.gz"
      sha256 "9674f186e5284a97833010b71bb7ca497e309c33320157ad55870078da8f2999"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.3-alpha/noida-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ab57d9ee5dbc1bd90d2faf050039a6536093a9bea2e0edd7701084ef09e336f6"
    end
  end

  def install
    bin.install "noida"
  end

  test do
    assert_match "noida", shell_output("#{bin}/noida --version")
  end
end
