# Generated by scripts/update-homebrew.sh; do not edit by hand.
class Noida < Formula
  desc "Terminal IDE built around Claude Code and Codex"
  homepage "https://github.com/its-banana-coder/noida"
  version "0.1.2-alpha"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.2-alpha/noida-aarch64-apple-darwin.tar.gz"
      sha256 "59e78449399c40a9bf0ef77228538b5dc57e87c409bc8a5afbf415509b741e7a"
    end
    on_intel do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.2-alpha/noida-x86_64-apple-darwin.tar.gz"
      sha256 "6b693302dd6ecb3d956b0c5ed9828ba42169eb6f8b418a3f37ab69dd63a78cbe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/its-banana-coder/noida/releases/download/v0.1.2-alpha/noida-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8fb574a953570382729ce8a8c48194159961ba1f2f877e2eb99b816eb871ef08"
    end
  end

  def install
    bin.install "noida"
  end

  test do
    assert_match "noida", shell_output("#{bin}/noida --version")
  end
end
